### ISSUE TITLE
Current version of acc-provision does not work with Python 3.10

### ISSUE THREAD

**Issue by mpsOxygen** [noironetworks/acc-provision#614]
This is do to how the Mapping function from collections is used:
>>> from collections import Mapping
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib64/python3.10/collections/__init__.py)

This is a deprecated method of using Mapping and should be migrate to the new method:
<stdin>:1: DeprecationWarning: Using or importing the ABCs
  from 'collections' instead of from 'collections.abc' is deprecated
  since Python 3.3, and in 3.10 it will stop working

**Comment by tomflynn** [comment]
Closed by #622
